#!/usr/bin/env bash

NAME='highload-stats'
VERSION='2'
HUB='oxmix'

case $1 in
  push)
    docker buildx create --name $NAME-builder --use
    docker buildx build --tag $HUB/$NAME:$VERSION \
                        --tag $HUB/$NAME:latest --push \
                        --platform linux/amd64,linux/arm64 .
    docker buildx rm $NAME-builder
    docker buildx prune -f
    ;;

  test)
    sh ./test.sh
    ;;

  *)
    echo "./build test|push"
    ;;
esac