name: Build and publish

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build containers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building images and push to hub
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64
          docker buildx create --use
          docker buildx build --tag oxmix/highload-stats:2 \
                              --tag oxmix/highload-stats:latest \
                              --push --platform linux/amd64,linux/arm64 .
